"""Add TweetUsers and Tweets tables

Revision ID: 1c3642bfed05
Revises:
Create Date: 2021-07-01 14:04:34.010883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c3642bfed05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_users',
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('screen_name', sa.String(), nullable=False),
        sa.Column('location', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('protected', sa.Boolean(), nullable=False),
        sa.Column('verified', sa.Boolean(), nullable=False),
        sa.Column('profile_banner_url', sa.String(), nullable=False),
        sa.Column('profile_image_url_https', sa.String(), nullable=False),
        sa.Column('default_profile', sa.Boolean(), nullable=False),
        sa.Column('default_profile_image', sa.Boolean(), nullable=False),
        sa.Column('withheld_in_countries', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
        sa.Column('withheld_scope', sa.String(), nullable=True),
        sa.Column('followers_count', sa.Integer(), nullable=False),
        sa.Column('friends_count', sa.Integer(), nullable=False),
        sa.Column('listed_count', sa.Integer(), nullable=False),
        sa.Column('favourites_count', sa.Integer(), nullable=False),
        sa.Column('statuses_count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_twitter_users_id'),
        'twitter_users',
        ['id'],
        unique=True
    )

    op.create_table('tweets',
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('truncated', sa.Boolean(), nullable=False),
        sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('place', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('entities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('extended_entities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('lang', sa.String(), nullable=True),
        sa.Column('in_reply_to_status_id', sa.Integer(), nullable=True),
        sa.Column('in_reply_to_user_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('quoted_status_id', sa.Integer(), nullable=True),
        sa.Column('retweeted_status_id', sa.Integer(), nullable=True),
        sa.Column('quote_count', sa.Integer(), nullable=True),
        sa.Column('reply_count', sa.Integer(), nullable=True),
        sa.Column('retweet_count', sa.Integer(), nullable=False),
        sa.Column('favorite_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['quoted_status_id'], ['tweets.id'], ),
        sa.ForeignKeyConstraint(['retweeted_status_id'], ['tweets.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['twitter_users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweets_id'), 'tweets', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweets_id'), table_name='tweets')
    op.drop_table('tweets')

    op.drop_index(op.f('ix_twitter_users_id'), table_name='twitter_users')
    op.drop_table('twitter_users')
    # ### end Alembic commands ###
